import Head from 'next/head';
import Layout from '/components/Layout';
import Table from '/components/Table';
import Footer from '../components/Footer';

export default function Home(props) {
  const { product } = props;
  return (
    <Layout>
      <Head>
        <title>Interview Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center flex-1 flex-shrink-0 bg-gray-100">
        <Table product={product} title='Question 1' noSearch={true}/>
        <Footer/>
      </div>
    </Layout>
  )
};

export async function getServerSideProps(context) {
  const endpoint = "https://screening.moduit.id/frontend/web/question/one";
  const product = await fetch(endpoint)
    .then((response) => response.json());

  return {
    props: {
      product: product || null
    }
  }
}
